# Site settings
title:          Imanol Schlag
description:    "Minimal Jekyll theme for storytellers"
url:            "https://ischlag.github.io"

# Author
author:
  name:         Imanol Schlag
  url:          https://ischlag.github.io
  email:        imanol.schlag@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       10
