title: Your Research Blog
description: Personal website with versioned articles
url: ""
baseurl: ""

author:
  name: Your Name
  email: your.email@example.com

markdown: kramdown
plugins:
  - jekyll-paginate

collections:
  articles:
    output: true
    permalink: /articles/:name/

sass:
  sass_dir: _sass
  style: compressed

paginate: 10